#!/usr/bin/python3
with open("secrets2env.sh", "w+") as script:
    script.write(
        "#!/bin/sh\n"
        ": ${ENV_SECRETS_DIR:=/run/secrets}\n"
        "function env_secret_debug()\n"
        "{\n"
        "   if [ ! -z \"$ENV_SECRETS_DEBUG\" ]; then\n"
        "        echo -e \"\\033[1m$@\\033[0m\"\n"
        "   fi\n"
        "}\n"
        "# usage: env_secret_expand VAR\n"
        "#    ie: env_secret_expand 'XYZ_DB_PASSWORD'\n"
        "# (will check for \"$XYZ_DB_PASSWORD\" variable value for a placeholder that defines the\n"
        "#  name of the docker secret to use instead of the original value. For example:\n"
        "# XYZ_DB_PASSWORD={{DOCKER_SECRET:my_db.secret}}\n"
        "env_secret_expand() {\n"
        "   var=\"$1\"\n"
        "   eval val=\\$$var\n"
        "   if secret_name=$(expr match \"$val\" \"'{{DOCKER_SECRET:\\([^}]\\+\\)}}'$\"); then\n"
        "       secret=\"${ENV_SECRETS_DIR}/${secret_name}\"\n"
        "       env_secret_debug \"Secret file for $var: $secret\"\n"
        "       if [ -f \"$secret\" ]; then\n"
        "           val=$(cat \"${secret}\")\n"
        "           export \"$var\"=\"$val\"\n"
        "           env_secret_debug \"Expanded variable: $var=$val\"\n"
        "       else\n"
        "           env_secret_debug \"Secret file does not exist! $secret\"\n"
        "       fi\n"
        "   fi\n"
        "}\n"
        "env_secrets_expand() {\n"
        "   for env_var in $(printenv | cut -f1 -d\"=\")\n"
        "   do\n"
        "       env_secret_expand $env_var\n"
        "   done\n"
        "   if [ ! -z \"$ENV_SECRETS_DEBUG\" ]; then\n"
        "       echo -e \"\\n\\033[1mExpanded environment variables\\033[0m\"\n"
        "       printenv\n"
        "   fi\n"
        "}\n"
        "env_secrets_expand")
